export enum Channel {
    ADD_FOLDER = 'ADD_FOLDER',
    GET_ROOT_FOLDERS = 'GET_ROOT_FOLDERS',
    GET_CHILDREN = 'GET_CHILDREN',
    GET_ENTITY = 'GET_ENTITY',
    GET_ENTITY_SIBLINGS = 'GET_ENTITY_SIBLINGS',
    UPDATE_PROGRESS = 'UPDATE_PROGRESS',
    UPDATE_FAVORITE = 'UPDATE_FAVORITE',
    GET_ALL_FAVORITES = 'GET_ALL_FAVORITES',
    DELETE_ENTITY = 'DELETE_ENTITY'
}

export const ApiKey = 'zenplayer-api';
export const DB_NAME = 'zenplayer.db';

export const QUERY_KEYS = {
    GET_ALL_ENTITY: 'GET_ALL_ENTITY',
    GET_ENTITY: 'GET_ENTITY',
    GET_ALL_FAVORITE_ENTITY: 'GET_ALL_FAVORITE_ENTITY'
};

export const APP_VERSION = '1.0';
