export enum Channel {
    ADD_FOLDER = 'ADD_FOLDER',
    GET_ROOT_FOLDERS = 'GET_ROOT_FOLDERS',
    GET_CHILDREN = 'GET_CHILDREN',
    GET_ENTITY = 'GET_ENTITY',
    NAVIGATE = 'NAVIGATE',
    GET_ENTITY_AND_SIBLING = 'GET_ENTITY_AND_SIBLING',
    UPDATE_PROGRESS = 'UPDATE_PROGRESS',
    UPDATE_FAVORITE = 'UPDATE_FAVORITE',
    GET_ALL_FAVORITES = 'GET_ALL_FAVORITES'
}

export const ApiKey = 'zenplayer-api';
export const DB_NAME = 'zenplayer.db';
